version: '3.4'

services:
  homecast:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - LIBGL_ALWAYS_INDIRECT=1
      - DISPLAY=host.docker.internal:0.0
      - NO_AT_BRIDGE=1
      - PULSE_SERVER=host.docker.internal
    ports:
      - 8121:8121
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/HomeCast/Cache:/home/homecast/cache

  homehook:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8122:8122
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro