#!/bin/bash
# This `debian/postinst` script is run post-installation
id -u homecast &>/dev/null || adduser --system homecast
chown homecast:homecast /home/homecast/.config/mpv
systemctl enable homecast
systemctl start homecast