#!/bin/bash
# This `debian/postinst` script is run post-installation
id -u homecast &>/dev/null || adduser --system homecast
usermod -aG audio,video,dialout homecast || true
chown homecast:homecast /home/homecast/.config/mpv
systemctl enable homecast
systemctl start homecast